spring.application.name=demo02
spring.datasource.url=jdbc:postgresql://postgres:5432/demo01
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8885